# Generated by Django 4.2.7 on 2026-07-29 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Jina')),
                ('organization', models.CharField(blank=True, default='', max_length=255, verbose_name='Shirika / Taasisi')),
                ('stakeholder_type', models.CharField(choices=[('government', 'Serikali / Ofisi'), ('local_government', 'Serikali za Mitaa'), ('community', 'Jamii / Kijiji'), ('ngo', 'NGO / Asasi'), ('private', 'Sekta Binafsi'), ('academic', 'Taasisi ya Elimu'), ('donor', 'Mfadhili / Mshirika'), ('other', 'Mwingine')], db_index=True, default='community', max_length=40, verbose_name='Aina ya Mdau')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Simu')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Barua pepe')),
                ('role', models.CharField(blank=True, default='', max_length=255, verbose_name='Wajibu / Maslahi')),
                ('region_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('district_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('ward_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('village_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Maelezo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Hai')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mdau',
                'verbose_name_plural': 'Wadau',
                'ordering': ['name', 'organization'],
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name'], name='wadau_stake_region__28a1a7_idx')],
            },
        ),
    ]
