# Generated by Django 4.2.7 on 2026-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='financial_year',
            field=models.CharField(db_index=True, default='2026/2027', max_length=32, verbose_name='Mwaka wa fedha'),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['financial_year'], name='wadau_stake_financi_6fe478_idx'),
        ),
    ]
