# Generated by Django 4.2.7 on 2026-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadau', '0002_financial_year_fillable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['category', 'name', 'organization'], 'verbose_name': 'Mdau', 'verbose_name_plural': 'Wadau'},
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='category',
            field=models.CharField(choices=[('planning_companies', 'Kampuni za Upangaji (Planning Companies)'), ('stakeholder_platform', 'Maandalizi ya Jukwaa la Wadau (Stakeholder Platform Preparation)'), ('ngos', 'NGOs — Local and International'), ('higher_education', 'Taasisi za Elimu ya Juu (Higher Education Institutions)'), ('financial_institutions', 'Taasisi za Kifedha (Financial Institutions)'), ('public_institutions', 'Taasisi, Mashirika ya Umma (Institutions / Public Corporations)'), ('sectoral_ministries', 'Wizara za Kisekta (Sectoral Ministries)')], db_index=True, default='stakeholder_platform', max_length=40, verbose_name='Kundi la Wadau'),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['category'], name='wadau_stake_categor_57242e_idx'),
        ),
    ]
