# Generated by Django 4.2.7 on 2026-07-16 05:51

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS detailed_planning;',
            reverse_sql='DROP SCHEMA IF EXISTS detailed_planning CASCADE;',
        ),
        migrations.CreateModel(
            name='VillageDetailedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Wilaya')),
                ('ward_name', models.CharField(db_index=True, max_length=255, verbose_name='Kata')),
                ('village_name', models.CharField(db_index=True, max_length=255, verbose_name='Kijiji')),
                ('total_landowners', models.PositiveIntegerField(default=0, verbose_name='Waliomiliki (jumla)')),
                ('female_landowners', models.PositiveIntegerField(default=0, verbose_name='Wanawake')),
                ('male_landowners', models.PositiveIntegerField(default=0, verbose_name='Wanaume')),
                ('children_under_18', models.PositiveIntegerField(default=0, verbose_name='Watoto chini ya 18')),
                ('identified_parcels', models.PositiveIntegerField(default=0, verbose_name='Viwanja vilivyotambuliwa')),
                ('unidentified_parcels', models.PositiveIntegerField(default=0, verbose_name='Viwanja visivyotambuliwa')),
                ('plan_status', models.CharField(choices=[('draft', 'Rasimu'), ('prepared', 'Imeandaliwa'), ('approved', 'Imeidhinishwa'), ('completed', 'Imekamilika')], default='draft', max_length=50)),
                ('plan_year', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mpango wa Kijiji',
                'verbose_name_plural': 'Mipango ya Vijiji',
                'db_table': '"detailed_planning"."village_plans"',
            },
        ),
        migrations.CreateModel(
            name='PlanningParcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Namba ya Kiwanja')),
                ('plot_sequence', models.PositiveIntegerField(default=0)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('village_name', models.CharField(db_index=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('is_identified', models.BooleanField(default=False, verbose_name='Imetambuliwa')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jina la Mmiliki')),
                ('owner_gender', models.CharField(blank=True, choices=[('M', 'Mwanaume'), ('F', 'Mwanamke'), ('U', 'Haijulikani')], max_length=1, null=True)),
                ('owner_age_category', models.CharField(blank=True, choices=[('adult', 'Mtu mzima (18+)'), ('child', 'Mtoto (chini ya 18)')], max_length=10, null=True)),
                ('owner_is_landowner', models.BooleanField(default=True, verbose_name='Ni mmiliki')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('village_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='detailed_planning.villagedetailedplan')),
            ],
            options={
                'verbose_name': 'Kiwanja cha Mpango',
                'verbose_name_plural': 'Viwanja vya Mpango',
                'db_table': '"detailed_planning"."planning_parcels"',
            },
        ),
        migrations.CreateModel(
            name='DistrictPlanningBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Wilaya')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('shapefile_name', models.CharField(blank=True, max_length=500, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mipaka ya Wilaya',
                'verbose_name_plural': 'Mipaka ya Wilaya',
                'db_table': '"detailed_planning"."district_boundaries"',
            },
        ),
        migrations.CreateModel(
            name='WardPlanningBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Wilaya')),
                ('ward_name', models.CharField(db_index=True, max_length=255, verbose_name='Kata')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('shapefile_name', models.CharField(blank=True, max_length=500, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mipaka ya Kata',
                'verbose_name_plural': 'Mipaka ya Kata',
                'db_table': '"detailed_planning"."ward_boundaries"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name'], name='ward_bounda_region__9caa51_idx')],
                'unique_together': {('region_name', 'district_name', 'ward_name')},
            },
        ),
        migrations.CreateModel(
            name='VillagePlanningBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Wilaya')),
                ('ward_name', models.CharField(db_index=True, max_length=255, verbose_name='Kata')),
                ('village_name', models.CharField(db_index=True, max_length=255, verbose_name='Kijiji')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('shapefile_name', models.CharField(blank=True, max_length=500, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mipaka ya Kijiji',
                'verbose_name_plural': 'Mipaka ya Kijiji',
                'db_table': '"detailed_planning"."village_boundaries"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='village_bou_region__179b00_idx')],
                'unique_together': {('region_name', 'district_name', 'ward_name', 'village_name')},
            },
        ),
        migrations.AddIndex(
            model_name='villagedetailedplan',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='village_pla_region__beb066_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='villagedetailedplan',
            unique_together={('region_name', 'district_name', 'ward_name', 'village_name')},
        ),
        migrations.AddIndex(
            model_name='planningparcel',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='planning_pa_region__972832_idx'),
        ),
        migrations.AddIndex(
            model_name='planningparcel',
            index=models.Index(fields=['is_identified'], name='planning_pa_is_iden_cfe572_idx'),
        ),
        migrations.AddIndex(
            model_name='planningparcel',
            index=models.Index(fields=['parcel_number'], name='planning_pa_parcel__c4e5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='districtplanningboundary',
            index=models.Index(fields=['region_name', 'district_name'], name='district_bo_region__97d67e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='districtplanningboundary',
            unique_together={('region_name', 'district_name')},
        ),
    ]
