# Generated by Django 4.2.7 on 2026-07-16 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detailed_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtplanningboundary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='planningparcel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='villagedetailedplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='villageplanningboundary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wardplanningboundary',
            name='created_by',
        ),
        migrations.AddField(
            model_name='districtplanningboundary',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji'),
        ),
        migrations.AddField(
            model_name='planningparcel',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji'),
        ),
        migrations.AddField(
            model_name='villagedetailedplan',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji'),
        ),
        migrations.AddField(
            model_name='villageplanningboundary',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji'),
        ),
        migrations.AddField(
            model_name='wardplanningboundary',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji'),
        ),
        migrations.CreateModel(
            name='PlanningShapefile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('boundary_level', models.CharField(choices=[('district', 'Wilaya'), ('ward', 'Kata'), ('village', 'Kijiji'), ('parcel', 'Kiwanja'), ('landuse', 'Matumizi ya Ardhi'), ('other', 'Nyingine')], db_index=True, max_length=20)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Wilaya')),
                ('ward_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Kata')),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Kijiji')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Jina la faili')),
                ('stored_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000, verbose_name='Njia ya faili')),
                ('file_format', models.CharField(choices=[('zip', 'ZIP (Shapefile)'), ('shp', 'SHP'), ('geojson', 'GeoJSON'), ('gpkg', 'GeoPackage'), ('kml', 'KML')], default='zip', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('feature_count', models.PositiveIntegerField(blank=True, null=True)),
                ('srid', models.IntegerField(default=32736)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('status', models.CharField(choices=[('uploaded', 'Imepakiwa'), ('processed', 'Imeshughulikiwa'), ('failed', 'Imeshindwa'), ('archived', 'Imehifadhiwa')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefiles', to='detailed_planning.districtplanningboundary')),
                ('village_boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefiles', to='detailed_planning.villageplanningboundary')),
                ('village_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefiles', to='detailed_planning.villagedetailedplan')),
                ('ward_boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefiles', to='detailed_planning.wardplanningboundary')),
            ],
            options={
                'verbose_name': 'Shapefile ya Mpango',
                'verbose_name_plural': 'Shapefile za Mpango',
                'db_table': '"detailed_planning"."planning_shapefiles"',
            },
        ),
        migrations.CreateModel(
            name='PlanningReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('report_type', models.CharField(choices=[('plan_summary', 'Muhtasari wa Mpango'), ('parcel_list', 'Orodha ya Viwanja'), ('boundary_map', 'Ramani ya Mipaka'), ('statistics', 'Takwimu'), ('pdf', 'PDF'), ('excel', 'Excel'), ('other', 'Nyingine')], db_index=True, default='plan_summary', max_length=30)),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Mkoa')),
                ('district_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Wilaya')),
                ('ward_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Kata')),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Kijiji')),
                ('report_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mwaka')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Jina la faili')),
                ('stored_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000, verbose_name='Njia ya faili')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rasimu'), ('generated', 'Imetengenezwa'), ('approved', 'Imeidhinishwa'), ('archived', 'Imehifadhiwa')], default='generated', max_length=20)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Muhtasari')),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shapefile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='detailed_planning.planningshapefile')),
                ('village_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='detailed_planning.villagedetailedplan')),
            ],
            options={
                'verbose_name': 'Ripoti ya Mpango',
                'verbose_name_plural': 'Ripoti za Mpango',
                'db_table': '"detailed_planning"."planning_reports"',
            },
        ),
        migrations.AddIndex(
            model_name='planningshapefile',
            index=models.Index(fields=['boundary_level'], name='planning_sh_boundar_e32718_idx'),
        ),
        migrations.AddIndex(
            model_name='planningshapefile',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='planning_sh_region__4dfcda_idx'),
        ),
        migrations.AddIndex(
            model_name='planningreport',
            index=models.Index(fields=['report_type'], name='planning_re_report__12190c_idx'),
        ),
        migrations.AddIndex(
            model_name='planningreport',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='planning_re_region__966408_idx'),
        ),
        migrations.AddIndex(
            model_name='planningreport',
            index=models.Index(fields=['report_year'], name='planning_re_report__d993c0_idx'),
        ),
    ]
