# Generated by Django 4.2.7 on 2026-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailed_planning', '0004_planningparcel_shapefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedetailedplan',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, default='2026/2027', max_length=32, verbose_name='Mwaka wa fedha'),
        ),
    ]
