# Generated by Django 4.2.7 on 2026-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailed_planning', '0005_financial_year_fillable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningreport',
            name='report_type',
            field=models.CharField(choices=[('plan_summary', 'Muhtasari wa Mpango'), ('parcel_list', 'Orodha ya Viwanja'), ('boundary_map', 'Ramani ya Mipaka'), ('statistics', 'Takwimu'), ('quarter_report', 'Quarter Report'), ('section_minutes', 'Minutes ya Section'), ('pdf', 'PDF'), ('excel', 'Excel'), ('other', 'Nyingine')], db_index=True, default='plan_summary', max_length=30),
        ),
    ]
