# Generated by Django 4.2.7 on 2026-07-29 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detailed_planning', '0007_minutes_za_vikao_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('financial_year', models.CharField(db_index=True, default='2026/2027', max_length=32, verbose_name='Mwaka wa fedha')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Jul–Sep)'), ('Q2', 'Q2 (Oct–Dec)'), ('Q3', 'Q3 (Jan–Mar)'), ('Q4', 'Q4 (Apr–Jun)')], db_index=True, max_length=2, verbose_name='Robo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Maelezo')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Jina la faili')),
                ('stored_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000, verbose_name='Njia ya faili')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quarter Report',
                'verbose_name_plural': 'Quarter Reports',
                'db_table': '"detailed_planning"."quarter_reports"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['financial_year', 'quarter'], name='quarter_rep_financi_b447fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Kichwa')),
                ('financial_year', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Mwaka wa fedha')),
                ('meeting_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Tarehe ya kikao')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Maelezo')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Jina la faili')),
                ('stored_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000, verbose_name='Njia ya faili')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minutes za Vikao',
                'verbose_name_plural': 'Minutes za Vikao',
                'db_table': '"detailed_planning"."meeting_minutes"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['financial_year', 'meeting_date'], name='meeting_min_financi_c31190_idx')],
            },
        ),
    ]
