# Generated by Django 4.2.7 on 2026-05-15 06:11

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TanzaniaAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_nam', models.CharField(db_index=True, max_length=100)),
                ('district_n', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ward_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('vil_mtaa_n', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
            ],
            options={
                'db_table': '"boundaries"."tanzania_administrative"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CCOImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"landuse"."cco_import_logs"',
            },
        ),
        migrations.CreateModel(
            name='CCOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(db_index=True, max_length=255)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('cco_name', models.CharField(max_length=255, verbose_name='Jina la CCO')),
                ('cco_id', models.CharField(max_length=50, unique=True, verbose_name='Kitambulisho cha CCO')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('villages_covered', models.TextField(blank=True, help_text='Vijiji anavyosimamia', null=True)),
                ('coverage_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"landuse"."cco_reports"',
            },
        ),
        migrations.CreateModel(
            name='LandUseImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"landuse"."import_logs"',
            },
        ),
        migrations.CreateModel(
            name='VillageBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Kijiji')),
                ('ward_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Kata')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Wilaya')),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Mkoa')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32736, verbose_name='Geometry')),
                ('area_ha', models.FloatField(blank=True, null=True, verbose_name='Eneo (Hekta)')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Idadi ya Wakazi')),
                ('households', models.IntegerField(blank=True, null=True, verbose_name='Idadi ya Kaya')),
                ('villages_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Msimbo wa Kijiji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Village Boundary',
                'verbose_name_plural': 'Village Boundaries',
                'db_table': '"landuse"."village_boundaries"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name'], name='village_bou_region__2d543d_idx'), models.Index(fields=['name'], name='village_bou_name_8cf457_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandUseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(db_index=True, max_length=255)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('has_landuse_plan', models.BooleanField(default=False, verbose_name='Imefanyiwa Land Use Plan')),
                ('landuse_plan_year', models.IntegerField(blank=True, null=True)),
                ('agriculture_area_ha', models.FloatField(default=0, verbose_name='Kilimo (Hekta)')),
                ('forest_area_ha', models.FloatField(default=0, verbose_name='Misitu (Hekta)')),
                ('urban_area_ha', models.FloatField(default=0, verbose_name='Miji/Makazi (Hekta)')),
                ('water_area_ha', models.FloatField(default=0, verbose_name='Maji (Hekta)')),
                ('wetland_area_ha', models.FloatField(default=0, verbose_name='Ardhi Oevu (Hekta)')),
                ('pasture_area_ha', models.FloatField(default=0, verbose_name='Malisho (Hekta)')),
                ('commercial_area_ha', models.FloatField(default=0, verbose_name='Biashara (Hekta)')),
                ('industrial_area_ha', models.FloatField(default=0, verbose_name='Viwanda (Hekta)')),
                ('other_area_ha', models.FloatField(default=0, verbose_name='Nyinginezo (Hekta)')),
                ('total_area_ha', models.FloatField(default=0, verbose_name='Jumla ya Eneo (Hekta)')),
                ('cco_count', models.IntegerField(default=0, verbose_name='Idadi ya CCO')),
                ('cco_percentage', models.FloatField(default=0, verbose_name='Asilimia ya CCO')),
                ('population', models.IntegerField(default=0, verbose_name='Idadi ya Wakazi')),
                ('households', models.IntegerField(default=0, verbose_name='Idadi ya Kaya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Use Report',
                'db_table': '"landuse"."land_use_reports"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name'], name='land_use_re_region__42b97c_idx'), models.Index(fields=['has_landuse_plan'], name='land_use_re_has_lan_798f25_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landuse_type', models.CharField(choices=[('agriculture', 'Kilimo'), ('forest', 'Misitu'), ('urban', 'Miji/Makazi'), ('water', 'Maji'), ('wetland', 'Ardhi Oevu'), ('pasture', 'Malisho'), ('commercial', 'Biashara'), ('industrial', 'Viwanda'), ('transport', 'Miadala'), ('mining', 'Madini'), ('conservation', 'Uhifadhi'), ('residential', 'Makazi'), ('mixed', 'Mchanganyiko'), ('other', 'Nyinginezo')], db_index=True, max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32736)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Land Use',
                'db_table': '"landuse"."land_use"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name', 'landuse_type'], name='land_use_region__3fff29_idx'), models.Index(fields=['year'], name='land_use_year_c505ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Jina')),
                ('infra_type', models.CharField(choices=[('school', 'Shule'), ('health_center', 'Kituo cha Afya'), ('dispensary', 'Zahanati'), ('hospital', 'Hospitali'), ('water_well', 'Kisima'), ('water_tap', 'Bomba la Maji'), ('road', 'Barabara'), ('bridge', 'Daraja'), ('market', 'Soko'), ('government_office', 'Ofisi ya Serikali'), ('police', 'Kituo cha Polisi'), ('religious', 'Kanisa/Msikiti'), ('electricity', 'Umeme'), ('telecom_tower', 'Mnara wa Mawasiliano'), ('bank', 'Benki'), ('fuel_station', 'Stesheni ya Mafuta')], db_index=True, max_length=50)),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32736, verbose_name='Location Point')),
                ('geom_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736, verbose_name='Area')),
                ('status', models.CharField(choices=[('planned', 'Iliopangwa'), ('under_construction', 'Inajengwa'), ('existing', 'Ipo'), ('damaged', 'Imeharibika'), ('non_functional', 'Haifanyi Kazi')], default='existing', max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'db_table': '"infrastructure"."infrastructure_facilities"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name', 'infra_type'], name='infrastruct_region__06cb57_idx'), models.Index(fields=['status'], name='infrastruct_status_5d6ad1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HamletBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Mtaa/Hamlet')),
                ('village_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Kijiji')),
                ('ward_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Kata')),
                ('district_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Wilaya')),
                ('region_name', models.CharField(db_index=True, max_length=255, verbose_name='Jina la Mkoa')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32736, verbose_name='Geometry')),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('hamlet_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Hamlet Boundary',
                'db_table': '"landuse"."hamlet_boundaries"',
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='hamlet_boun_region__267360_idx')],
            },
        ),
    ]
