# Generated by Django 4.2.7 on 2026-05-15 07:59

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('landuse', 'Land Use Shapefile'), ('village_boundary', 'Village Boundary Shapefile'), ('hamlet_boundary', 'Hamlet Boundary Shapefile'), ('social_services', 'Social Services Shapefile'), ('parcels', 'Parcels Shapefile'), ('infrastructure', 'Infrastructure Shapefile'), ('cco_data', 'CCO Excel Data'), ('other', 'Other')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('import_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"landuse"."import_logs"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Namba ya Kiwanja')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jina la Mmiliki')),
                ('owner_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kitambulisho cha Mmiliki')),
                ('village_name', models.CharField(db_index=True, max_length=255)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32736)),
                ('area_ha', models.FloatField(blank=True, null=True, verbose_name='Eneo (Hekta)')),
                ('landuse_type', models.CharField(blank=True, choices=[('agriculture', 'Kilimo'), ('pasture', 'Malisho'), ('forest', 'Misitu'), ('conservation', 'Uhifadhi'), ('residential', 'Makazi'), ('commercial', 'Biashara'), ('other', 'Nyingine')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('registered', 'Imesajiliwa ✅'), ('pending', 'Inaendelea ⏳'), ('disputed', 'Ina Mgogoro ⚠️'), ('reserved', 'Hifadhi 🛡️'), ('expired', 'Muda Umeisha ⏰')], default='registered', max_length=50)),
                ('cco_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='CCO Anayesimamia')),
                ('cco_id', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='parcel_certificates/')),
                ('survey_plan', models.FileField(blank=True, null=True, upload_to='survey_plans/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'db_table': '"landuse"."parcels"',
            },
        ),
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Jina la Huduma')),
                ('service_category', models.CharField(choices=[('education', '📚 Elimu'), ('health', '🏥 Afya'), ('water', '💧 Maji'), ('market', '🛒 Masoko'), ('government', '🏛️ Serikali'), ('religious', '⛪ Dini'), ('sports', '⚽ Michezo'), ('security', '👮 Usalama'), ('infrastructure', '🏗️ Miundombinu'), ('other', '📌 Nyingine')], db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('school_primary', 'Shule ya Msingi'), ('school_secondary', 'Shule ya Sekondari'), ('school_vocational', 'Shule ya Ufundi'), ('health_dispensary', 'Zahanati'), ('health_center', 'Kituo cha Afya'), ('health_hospital', 'Hospitali'), ('water_well', 'Kisima'), ('water_tap', 'Bomba la Maji'), ('water_dam', 'Bwawa'), ('market', 'Soko'), ('market_livestock', 'Soko la Mifugo'), ('government_office', 'Ofisi ya Serikali'), ('police', 'Kituo cha Polisi'), ('religious_church', 'Kanisa'), ('religious_mosque', 'Msikiti'), ('sports_field', 'Uwanja wa Michezo'), ('other', 'Nyingine')], db_index=True, max_length=50)),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ward_name', models.CharField(db_index=True, max_length=255)),
                ('district_name', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32736)),
                ('geom_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Nzuri Sana'), ('good', 'Nzuri'), ('average', 'Wastani'), ('poor', 'Dhaifu'), ('damaged', 'Imeharibika'), ('non_functional', 'Haifanyi Kazi')], default='average', max_length=50)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='social_services/')),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='social_services_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Service',
                'verbose_name_plural': 'Social Services',
                'db_table': '"landuse"."social_services"',
            },
        ),
        migrations.DeleteModel(
            name='CCOImportLog',
        ),
        migrations.DeleteModel(
            name='LandUseImportLog',
        ),
        migrations.AlterModelOptions(
            name='ccoreport',
            options={'verbose_name': 'CCO Report'},
        ),
        migrations.AlterModelOptions(
            name='landuse',
            options={'verbose_name': 'Land Use Data', 'verbose_name_plural': 'Land Use Data'},
        ),
        migrations.RenameIndex(
            model_name='landuse',
            new_name='land_use_da_region__70d242_idx',
            old_name='land_use_region__3fff29_idx',
        ),
        migrations.RenameIndex(
            model_name='landuse',
            new_name='land_use_da_year_b40988_idx',
            old_name='land_use_year_c505ef_idx',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='contact',
        ),
        migrations.AddField(
            model_name='ccoreport',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cco_certificates/'),
        ),
        migrations.AddField(
            model_name='ccoreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cco_photos/'),
        ),
        migrations.AddField(
            model_name='ccoreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hamletboundary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamletboundary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='geom_line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=32736),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='length_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Urefu (Km)'),
        ),
        migrations.AddField(
            model_name='landuse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landusereport',
            name='agriculture_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='landusereport',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landusereport',
            name='forest_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='landusereport',
            name='plan_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landusereport',
            name='urban_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft - Rasimu'), ('pending_review', 'Inasubiri Ukaguzi'), ('approved', 'Imeidhinishwa ✅'), ('rejected', 'Imekataliwa ❌'), ('expired', 'Muda Umeisha ⏰'), ('under_review', 'Inakaguliwa 🔍')], default='draft', max_length=50, verbose_name='Hali ya Idhini'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='Inahitaji Ukaguzi'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='plan_expiry_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mwaka wa Kuisha Mpango'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='village_plans/%Y/%m/', verbose_name='PDF ya Mpango'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='plan_preparation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mwaka wa Kuandaa Mpango'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='plan_status',
            field=models.CharField(choices=[('prepared', 'Kimeandaliwa'), ('not_prepared', 'Hakijaandaliwa'), ('in_progress', 'Inaendelea')], default='not_prepared', max_length=50, verbose_name='Hali ya Mpango'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='review_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Sababu ya Ukaguzi'),
        ),
        migrations.AddField(
            model_name='villageboundary',
            name='supporting_docs',
            field=models.FileField(blank=True, null=True, upload_to='village_docs/%Y/%m/', verbose_name='Nyaraka Zingine'),
        ),
        migrations.AlterField(
            model_name='ccoreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ccoreport',
            name='villages_covered',
            field=models.TextField(blank=True, help_text='Vijiji anavyosimamia (tenganisha kwa koma)', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32736),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='geom_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32736),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='infra_type',
            field=models.CharField(choices=[('road', '🛣️ Barabara'), ('bridge', '🌉 Daraja'), ('electricity', '⚡ Umeme'), ('telecom', '📡 Mawasiliano'), ('railway', '🚂 Reli'), ('port', '⚓ Bandari'), ('airport', '✈️ Uwanja wa Ndege'), ('water_supply', '💧 Usambazaji Maji'), ('sewage', '🚽 Maji Taka'), ('other', '📌 Nyingine')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='status',
            field=models.CharField(choices=[('planned', 'Iliopangwa'), ('under_construction', 'Inajengwa'), ('operational', 'Inafanya Kazi'), ('damaged', 'Imeharibika'), ('non_functional', 'Haifanyi Kazi')], default='operational', max_length=50),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='landuse_type',
            field=models.CharField(choices=[('agriculture', '🌾 Kilimo'), ('forest', '🌲 Misitu'), ('urban', '🏙️ Miji/Makazi'), ('water', '💧 Maji'), ('wetland', '🌿 Ardhi Oevu'), ('pasture', '🐄 Malisho'), ('commercial', '🏪 Biashara'), ('industrial', '🏭 Viwanda'), ('transport', '🛣️ Miadala'), ('mining', '⛏️ Madini'), ('conservation', '🦁 Uhifadhi'), ('residential', '🏠 Makazi'), ('mixed', '🔄 Mchanganyiko'), ('other', '📌 Nyinginezo')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='agriculture_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='cco_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='cco_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='commercial_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='forest_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='has_landuse_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='households',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='industrial_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='other_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='pasture_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='total_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='urban_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='water_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusereport',
            name='wetland_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='ccoreport',
            index=models.Index(fields=['cco_id', 'cco_name'], name='cco_reports_cco_id_63d19d_idx'),
        ),
        migrations.AddIndex(
            model_name='ccoreport',
            index=models.Index(fields=['district_name', 'ward_name', 'village_name'], name='cco_reports_distric_16b89d_idx'),
        ),
        migrations.AddIndex(
            model_name='ccoreport',
            index=models.Index(fields=['is_active'], name='cco_reports_is_acti_d4fcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='hamletboundary',
            index=models.Index(fields=['name'], name='hamlet_boun_name_9c045d_idx'),
        ),
        migrations.AddIndex(
            model_name='villageboundary',
            index=models.Index(fields=['approval_status', 'plan_status'], name='village_bou_approva_e83e54_idx'),
        ),
        migrations.AlterModelTable(
            name='infrastructure',
            table='"landuse"."infrastructure_facilities"',
        ),
        migrations.AlterModelTable(
            name='landuse',
            table='"landuse"."land_use_data"',
        ),
        migrations.AddIndex(
            model_name='socialservice',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'service_category'], name='social_serv_region__85a465_idx'),
        ),
        migrations.AddIndex(
            model_name='socialservice',
            index=models.Index(fields=['service_type'], name='social_serv_service_3c0fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['parcel_number'], name='parcels_parcel__f79e15_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='parcels_region__8ab35f_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['cco_name', 'cco_id'], name='parcels_cco_nam_9ccdec_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcels_status_ed18a4_idx'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
