# Generated by Django 4.2.7 on 2026-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_importlog_parcel_socialservice_delete_ccoimportlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageboundary',
            name='approval_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
