# Generated by Django 4.2.7 on 2026-05-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_villageboundary_approval_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccoreport',
            options={'managed': False, 'verbose_name': 'CCO Report'},
        ),
        migrations.AlterModelOptions(
            name='hamletboundary',
            options={'managed': False, 'verbose_name': 'Hamlet Boundary'},
        ),
        migrations.AlterModelOptions(
            name='importlog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'managed': False, 'verbose_name': 'Infrastructure'},
        ),
        migrations.AlterModelOptions(
            name='landuse',
            options={'managed': False, 'verbose_name': 'Land Use Data', 'verbose_name_plural': 'Land Use Data'},
        ),
        migrations.AlterModelOptions(
            name='landusereport',
            options={'managed': False, 'verbose_name': 'Land Use Report'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'managed': False, 'verbose_name': 'Parcel', 'verbose_name_plural': 'Parcels'},
        ),
        migrations.AlterModelOptions(
            name='socialservice',
            options={'managed': False, 'verbose_name': 'Social Service', 'verbose_name_plural': 'Social Services'},
        ),
        migrations.AlterModelOptions(
            name='villageboundary',
            options={'managed': False, 'verbose_name': 'Village Boundary', 'verbose_name_plural': 'Village Boundaries'},
        ),
    ]
