# Generated by Django 4.2.7 on 2026-06-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_ccoreport_options_alter_hamletboundary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling (TSH)'), ('USD', 'US Dollar')], default='TZS', max_length=3)),
                ('payment_method', models.CharField(choices=[('card', 'Kadi (Card)'), ('merchant', 'Pay Merchant')], max_length=20)),
                ('provider', models.CharField(blank=True, default='demo', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('paid', 'Imelipwa'), ('failed', 'Imeshindwa'), ('cancelled', 'Imefutwa')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('download_data_type', models.CharField(max_length=50)),
                ('download_format', models.CharField(max_length=30)),
                ('download_region', models.CharField(blank=True, default='', max_length=255)),
                ('download_district', models.CharField(blank=True, default='', max_length=255)),
                ('download_ward', models.CharField(blank=True, default='', max_length=255)),
                ('payer_name', models.CharField(blank=True, default='', max_length=255)),
                ('payer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('payer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mchango wa Kupakua',
                'verbose_name_plural': 'Michango ya Kupakua',
                'ordering': ['-created_at'],
            },
        ),
    ]
