# Generated by Django 4.2.7 on 2026-07-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(help_text='Inahitajika wakati wa kujisajili. Shared kwa sehemu yote.', max_length=128, verbose_name='Nambari ya Usajili (Section)')),
                ('login_code', models.CharField(help_text='Inahitajika wakati wa login pamoja na username/password.', max_length=128, verbose_name='Nambari ya Kuingia (Taasisi)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Access Config',
                'verbose_name_plural': 'Section Access Config',
            },
        ),
    ]
