# Generated by Django 4.2.7 on 2026-07-18 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS detailed_planning;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='LandConflictCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('conflict_type', models.CharField(choices=[('boundary', 'Mpaka'), ('ownership', 'Umiliki'), ('inheritance', 'Urithi'), ('land_use', 'Matumizi ya Ardhi'), ('encroachment', 'Uvamizi'), ('other', 'Nyingine')], db_index=True, default='boundary', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Wazi'), ('investigating', 'Inachunguzwa'), ('mediation', 'Usuluhishi'), ('resolved', 'Imesuluhishwa'), ('closed', 'Imefungwa')], db_index=True, default='open', max_length=30)),
                ('region_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('district_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('ward_name', models.CharField(blank=True, default='', max_length=100)),
                ('village_name', models.CharField(blank=True, default='', max_length=100)),
                ('complainant', models.CharField(blank=True, default='', max_length=255)),
                ('respondent', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID ya mtumiaji')),
            ],
            options={
                'verbose_name': 'Kesi ya Mgogoro wa Ardhi',
                'verbose_name_plural': 'Kesi za Migogoro ya Ardhi',
                'db_table': '"detailed_planning"."land_conflict_cases"',
                'ordering': ['-created_at'],
            },
        ),
    ]
