# Generated by Django 4.2.7 on 2026-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landconflictcase',
            options={'ordering': ['-started_date', '-created_at'], 'verbose_name': 'Kesi ya Mgogoro wa Ardhi', 'verbose_name_plural': 'Kesi za Migogoro ya Ardhi'},
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='conflict_source',
            field=models.CharField(choices=[('unclear_boundary', 'Mipaka isiyoeleweka'), ('no_documents', 'Ukosefu wa hati / usajili'), ('inheritance_dispute', 'Mgogoro wa urithi'), ('land_grabbing', 'Kunyakua ardhi'), ('population_pressure', 'Msongamano wa watu'), ('resource_competition', 'Ushindani wa rasilimali'), ('resettlement', 'Uhamishaji / makazi mapya'), ('investor_project', 'Mradi wa uwekezaji'), ('admin_decision', 'Uamuzi wa utawala'), ('other', 'Chanzo kingine')], db_index=True, default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='resolution_details',
            field=models.TextField(blank=True, default='', verbose_name='Maelezo ya mbinu za utatuzi'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='resolution_method',
            field=models.CharField(choices=[('mediation', 'Usuluhishi wa kijamii'), ('village_council', 'Baraza la Kijiji'), ('ward_tribunal', 'Baraza la Kata'), ('district_land', 'Ofisi ya Ardhi ya Wilaya'), ('court', 'Mahakama'), ('negotiation', 'Majadiliano'), ('survey', 'Upimaji / mipaka mpya'), ('compensation', 'Fidia'), ('other', 'Nyingine'), ('none', 'Bado hakuna')], default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarehe mgogoro ulipoanzia'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='unresolved_reason',
            field=models.TextField(blank=True, default='', verbose_name='Kwanini bado haujatatuliwa'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='conflict_type',
            field=models.CharField(choices=[('boundary', 'Mpaka wa viwanja / vijiji'), ('ownership', 'Umiliki wa ardhi'), ('inheritance', 'Urithi'), ('land_use', 'Matumizi ya ardhi'), ('encroachment', 'Uvamizi / uvamizi wa mipaka'), ('grazing', 'Malisho / migogoro ya wafugaji'), ('water', 'Maji / rasilimali'), ('investor', 'Uwekezaji / wawekezaji'), ('multiple', 'Migogoro mingi'), ('other', 'Nyingine')], db_index=True, default='boundary', max_length=30),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='status',
            field=models.CharField(choices=[('open', 'Wazi / bado haujatatuliwa'), ('investigating', 'Inachunguzwa'), ('mediation', 'Usuluhishi unaendelea'), ('resolved', 'Umetatuliwa'), ('closed', 'Imefungwa')], db_index=True, default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='village_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='ward_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='landconflictcase',
            index=models.Index(fields=['region_name', 'district_name', 'ward_name', 'village_name'], name='land_confli_region__450054_idx'),
        ),
    ]
