# Generated by Django 4.2.7 on 2026-07-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0004_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigogoroConflictSource',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Chanzo cha Mgogoro',
                'verbose_name_plural': 'Vyanzo vya Migogoro',
                'db_table': '"detailed_planning"."migogoro_conflict_sources"',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MigogoroConflictType',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Aina ya Mgogoro',
                'verbose_name_plural': 'Aina za Migogoro',
                'db_table': '"detailed_planning"."migogoro_conflict_types"',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MigogoroFinancialYear',
            fields=[
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mwaka wa Fedha (Migogoro)',
                'verbose_name_plural': 'Miaka ya Fedha (Migogoro)',
                'db_table': '"detailed_planning"."migogoro_financial_years"',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='MigogoroResolutionMethod',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_resolved_only', models.BooleanField(default=True, help_text='Onyesha tu wakati mgogoro umetatuliwa')),
            ],
            options={
                'verbose_name': 'Mbinu ya Utatuzi',
                'verbose_name_plural': 'Mbinu za Utatuzi',
                'db_table': '"detailed_planning"."migogoro_resolution_methods"',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='financial_year',
            field=models.CharField(db_index=True, default='2026/2027', max_length=9, verbose_name='Mwaka wa fedha'),
        ),
        migrations.AddIndex(
            model_name='landconflictcase',
            index=models.Index(fields=['financial_year', 'conflict_type'], name='land_confli_financi_061293_idx'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='conflict_source_ref',
            field=models.ForeignKey(blank=True, db_column='conflict_source_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='land_conflicts.migogoroconflictsource'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='conflict_type_ref',
            field=models.ForeignKey(blank=True, db_column='conflict_type_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='land_conflicts.migogoroconflicttype'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='financial_year_ref',
            field=models.ForeignKey(blank=True, db_column='financial_year_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='land_conflicts.migogorofinancialyear'),
        ),
        migrations.AddField(
            model_name='landconflictcase',
            name='resolution_method_ref',
            field=models.ForeignKey(blank=True, db_column='resolution_method_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='land_conflicts.migogororesolutionmethod'),
        ),
    ]
