# Generated by Django 4.2.7 on 2026-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0005_migogoro_lookup_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='landconflictcase',
            name='conflict_type_other',
            field=models.CharField(blank=True, default='', help_text='Jaza ikiwa aina ni Mingineyo', max_length=255, verbose_name='Aina nyingine (eleza)'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='conflict_type',
            field=models.CharField(choices=[('village_boundary', '1. Migogoro wa Mipaka wa Vijiji'), ('farmers_pastoralists', '2. Mgogoro wa Wakulima na Wafugaji'), ('resources', '3. Mgogoro wa Rasilimali'), ('other', '4. Mingineyo')], db_index=True, default='village_boundary', max_length=40),
        ),
    ]
