# Generated by Django 4.2.7 on 2026-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0007_merge_into_single_migogoro_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='landconflictcase',
            new_name='migogoro_region__38c08c_idx',
            old_name='land_confli_region__450054_idx',
        ),
        migrations.RenameIndex(
            model_name='landconflictcase',
            new_name='migogoro_financi_6149ff_idx',
            old_name='land_confli_financi_061293_idx',
        ),
    ]
