# Generated by Django 4.2.7 on 2026-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0008_rename_land_confli_region__450054_idx_migogoro_region__38c08c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landconflictcase',
            name='village_name_other',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Kijiji kingine kwa mgogoro wa mipaka (baina ya vijiji)', max_length=100, verbose_name='Kijiji cha pili'),
        ),
    ]
