# Generated by Django 4.2.7 on 2026-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0009_village_name_other_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landconflictcase',
            name='complainant',
            field=models.CharField(blank=True, default='', help_text='Mfano: Ifunde', max_length=255, verbose_name='Mlalamikaji'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='conflict_source',
            field=models.TextField(blank=True, default='', verbose_name='Chanzo cha Mgogoro'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='resolution_method',
            field=models.TextField(blank=True, default='', verbose_name='Mbinu za utatuzi'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='respondent',
            field=models.CharField(blank=True, default='', help_text='Mfano: Njaro', max_length=255, verbose_name='Mlalamikiwa'),
        ),
        migrations.AlterField(
            model_name='landconflictcase',
            name='village_name_other',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
