# Generated by Django 4.2.7 on 2026-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_conflicts', '0011_convert_chanzo_utatuzi_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landconflictcase',
            name='financial_year',
            field=models.CharField(db_index=True, default='2026/2027', max_length=32, verbose_name='Mwaka wa fedha'),
        ),
    ]
