# Generated by Django 4.2.7 on 2026-05-13 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(blank=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.region'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.ward')),
            ],
            options={
                'unique_together': {('ward', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
    ]
