# Generated by Django 4.2.7 on 2026-07-18 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazetteVillage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(db_index=True, max_length=100)),
                ('district_name', models.CharField(db_index=True, max_length=150)),
                ('ward_name', models.CharField(db_index=True, max_length=150)),
                ('village_name', models.CharField(db_index=True, max_length=150)),
                ('unit_type', models.CharField(choices=[('village', 'Kijiji'), ('mtaa', 'Mtaa')], default='village', max_length=20)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kijiji (Gazeti)',
                'verbose_name_plural': 'Vijiji (Gazeti)',
                'db_table': 'locations_gazette_village',
                'ordering': ['region_name', 'district_name', 'ward_name', 'village_name'],
                'indexes': [models.Index(fields=['region_name', 'district_name', 'ward_name'], name='locations_g_region__190156_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='gazettevillage',
            constraint=models.UniqueConstraint(fields=('region_name', 'district_name', 'ward_name', 'village_name'), name='uniq_gazette_village_hierarchy'),
        ),
    ]
